version: '3.8'

services:
  php:
    build:
      context: ./frontend
      dockerfile: Dockerfile.php
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - app-network  

  mysql:
    build:
      context: ./backend/database
      dockerfile: Dockerfile.backend
    ports:
      - "3306:3306"
    env_file:
      - ./mysql/.env
    volumes:
      - mysql-data:/var/lib/mysql
      - ./backend/database/db.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network  

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge
