name: Build and Push Frontend + Backend (One Repo)

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: us-east-1
  ECR_REPO: my-app-repo

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push Frontend
        run: |
          IMAGE_TAG=${GITHUB_SHA::7}
          FRONTEND_URI=${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPO }}:frontend-$IMAGE_TAG
          
          docker build -t $FRONTEND_URI -f ./frontend/Dockerfile.php ./frontend
          docker push $FRONTEND_URI

      - name: Build and Push Backend
        run: |
          IMAGE_TAG=${GITHUB_SHA::7}
          BACKEND_URI=${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPO }}:backend-$IMAGE_TAG
          
          docker build -t $BACKEND_URI -f ./backend/Dockerfile.backend ./backend
          docker push $BACKEND_URI

