name: Docker Build and Trivy Scan

on:
  push:
    branches: [ main ]

jobs:
  docker-trivy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: image
          image-ref: demystifier803/social12-php:latest
          format: table
          severity: CRITICAL,HIGH
          
      - name: Upload Trivy Report
        uses: actions/upload-artifact@v4
        with:
         name: trivy-scan-report
         path: trivy-report.json   

